[package]
name = "falcon-bms-control-server"
edition = "2024"

build = "build.rs"

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build", "cargo", "rustc", "si"] }
anyhow = "*"

# [lib]
# name = "falcon_key_file"
# path = "src/lib/falcon-key-file/src/lib.rs"

[dependencies]
# bms-sm = { version = "*", path = "src/lib/bms-rs" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
# winapi = "*"
# user32-sys = "*"
enigo = "0.6"
seahash = "4.1.0"
levenshtein = "1.0.5"
figment = { version = "0.10", features = ["toml"]}
serde = {version = "1", features = ["derive"]}
rusty_enet = "0.4.0"
tokio-util = "0.7.16"
rmp-serde = "1.3.0"
